### PR TITLE
Clean up syntax

### PR DESCRIPTION
**Pull request by bangyen**
- Changed `if` statements to `elif` or `else` statements where needed.
- Removed redundant parentheses around `if` statement conditions.
- Created `res_dict` to cut down on repetitive code when evaluating mathematical statements.
- Other minor changes.

### CODE REVIEW

**Comment by Wafelack** [comment]
As you like it but this version will no longer be supported, i've created a branch with a new mean of parsing and a new syntax

**Comment by bangyen** [comment]
Should I update that branch as well?

**Comment by Wafelack** [comment]
As you like it, i have almost gave up this project

**Comment by bangyen** [comment]
How come? It's a really interesting project! Anything is salvageable.

**Comment by Wafelack** [comment]
Yeah but i don't have enough time to maintain it, but i'll try these holidays.

**Pull request merged**
